schoolproject/schoolproject/credentials/urls.py
from . import views
from django.urls import path
app_name='credentials'

urlpatterns = [

    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('form/',views.form,name='form'),
    path('logout/',views.logout,name='logout'),
    path('newpage/',views.newpage,name='newpage'),
    path('loginbutton/',views.loginbutton,name='loginbutton'),
    path('new/',views.new,name='new'),
]

schoolproject/schoolproject/schoolapp/urls.py
from . import views
from django.urls import path
app_name='schoolapp'
urlpatterns = [

    path('',views.demo,name='demo'),
]

schoolproject/schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
    path('credentials/',include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

schoolproject/schoolproject/credentials/models.py
from django.db import models

# Create your models here.



class school_tab(models.Model):
    name=models.CharField(max_length=250)
    dob=models.DateField()
    age=models.IntegerField()
    gender=models.TextField()
    phoneno=models.TextField()
    email=models.EmailField()
    address = models.TextField(max_length=250)
    debitnotebook = models.TextField(default=True)
    pen = models.TextField(default=True)
    exampaper = models.TextField(default=True)



    def __str__(self):
        return self.name

schoolproject/schoolproject/credentials/views.py
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


from .models import school_tab


# Create your views here.
def form(request):
    if request.method == 'POST':
        name=request.POST.get('name','')
        dob = request.POST.get('dob','')
        age = request.POST.get('age','')
        gender = request.POST.get('gender','')
        phoneno = request.POST.get('phoneno','')
        email = request.POST.get('email','')
        address = request.POST.get('address','')
        debitnotebook = request.POST.get('debitnotebook','')
        pen = request.POST.get('pen','')
        exampaper = request.POST.get('exampaper','')



        School_tab=school_tab(name=name,dob=dob,age=age,gender=gender,
                                        phoneno=phoneno,email=email,address=address,debitnotebook=debitnotebook,
                                        pen=pen,exampaper=exampaper,)
        School_tab.save();
        if debitnotebook == 'on':
            True
        else:
            False
        messages.info(request,"Order Confirmed")
    return render(request,"form.html")

def login(request):
    if request.method=='POST':
        username=request.POST['user']
        password=request.POST['pd']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return render(request,"newpage.html")
        else:
            messages.info(request,"INVALID CREDENTIALS")
            return render(request,"login.html")
    return render(request,"login.html")
def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        pwd = request.POST['pd']
        cpd = request.POST['cpd']
        if pwd==cpd:
            if User.objects.filter(username=username).exists():
                messages.info(request,"USERNAME TAKEN")
                return render(request,"register.html")
            else:
                user = User.objects.create_user(username=username, password=pwd)
                user.save();
                messages.info(request, "USER REGISTRATION SUCCESSFULL")
                return render(request,"login.html")
        else:
            messages.info(request, "Password Not Matching")
            return render(request,"register.html")
    return render(request,"register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')
def newpage(request):
    return render(request,"newpage.html")
def loginbutton(request):
    return render(request,"login.html")
def new(request):
    return render(request,"new.html")

schoolproject/schoolproject/schoolapp/views.py
from django.shortcuts import render

# Create your views here.
def demo(request):
    return render(request,"index.html")

schoolproject/schoolproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<script>
var subjectObject = {
  "Computer Science": {
    "Python": [],
    "JavaScript": []
  },
  "English": {
    "Literature": []
  },
  "Commerce": {
    "B.Com": [],
    "M.Com": []
  },
  "Electronics": {
    "Diploma Es": [],
    "B.Tech Es": []
  },
  "Electrical": {
    "Diploma Es": [],
    "B.Tech Es": []
    }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");

  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns

    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
    //empty Chapters dropdown

    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {

    }
  }
}
</script>

</head>
<body style="background-image:url({% static 'img/bg.jpg' %})">
<center>
    <br><h1 style="color:#118FC9;font-family:Garamond"><u>STORE</u></h1><br>
        <form action="{% url 'credentials:form' %}" method="post" >
            {% csrf_token %}
            <label><b>Name:</b></label>&nbsp;&nbsp;
            <input type="text" name="name" placeholder="Name"><br><br>
            <label><b>Dob:&nbsp&nbsp&nbsp&nbsp&nbsp</b></label>
            <input type="text" name="dob" placeholder="Dob"><br><br>
            <label><b>Age:&nbsp&nbsp&nbsp&nbsp&nbsp</b></label>&nbsp;
            <input type="text" name="age" placeholder="Age"><br><br>
            <label><b>Gender:</b></label>&nbsp;
            <input type="text" name="gender" placeholder="Gender"><br><br>
            <label><b>Phone:&nbsp&nbsp</b></label>
            <input type="text" name="phoneno" placeholder="Phone-No"><br><br>
            <label><b>E-mail:&nbsp&nbsp</b></label>
            <input type="email" name="email" placeholder="Em@il"><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <label><b>Address:</b></label>
            <input type="address" name="address" placeholder="Address"><br><br>

            <label><b>Department</b></label>
            <select name="subject" id="subject">
                 <option value="" selected="selected" name="subject">Select Department</option>
            </select>
            <br><br>
            <label><b>Course</b></label>
            <select name="topic" id="topic">
                <option value="" selected="selected" name="subject">Select Course</option>
            </select>
            <br>

            <h5 style="color:white;font-family:Armond">Materials Provide</h5>
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <input type="checkbox" name="debitnotebook">
            <label><b>Debit Notebook</b></label><br>

            <input type="checkbox" name="pen">
            <label><b>Pen</b></label><br>
            &nbsp&nbsp&nbsp&nbsp&nbsp
            &nbsp&nbsp &nbsp&nbsp&nbsp&nbsp
            <input type="checkbox" name="exampaper">
            <label><b>Exam Paper</b></label><br>

            <button class="btn btn-primary" type="submit">Submit</button>
            <a class="btn btn-primary" href="/" role="button">Logout</a>




</form>
     {% for msg in messages %}
    <h2 style="color:white;">{{msg}}</h2>
    {% endfor %}
    <a href="/"><b>Click Here to return Home Page..</b>></a>
</center>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

schoolproject/schoolproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body style="background-image:url({% static 'img/log.jpg' %})">
<center>
  <form action="{% url 'credentials:login' %}" method='post'>
    {% csrf_token %}
    <br><br><br><br>
    <h1 style="color:white;font-family:Garamond"><u>LOG IN</u></h1><br><br>
    <br>
    <input type="text" name="user" placeholder="Enter Username"><br><br><br>
    <input type="password" name="pd" placeholder="Enter Password"><br><br><br>
    <input type="submit" value="LOGIN">

    <a href="{% url 'credentials:register' %}"><h2 style="color:white;font-family:Garamond">Register</h2></a>
  </form>
  {% for msg in messages %}
    <h2 style="color:white;">{{msg}}</h2>
    {% endfor %}
</center>

</body>
</html>

schoolproject/schoolproject/templates/new.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
var subjectObject = {
  "Computer Science": {
    "Python": [],
    "JavaScript": []
  },
  "English": {
    "Literature": []
  },
  "Commerce": {
    "B.Com": [],
    "M.Com": []
  },
  "Electronics": {
    "Diploma Es": [],
    "B.Tech Es": []
  },
  "Electrical": {
    "Diploma Es": [],
    "B.Tech Es": []
    }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");

  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns

    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
    //empty Chapters dropdown

    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {

    }
  }
}
</script>
</head>
<body>


<form name="form1" id="form1" action="{% url 'credentials:login' %}">
Department <select name="subject" id="subject">
    <option value="" selected="selected">Select Department</option>
  </select>
  <br><br>
Course <select name="topic" id="topic">
    <option value="" selected="selected">Select Course</option>
  </select>
  <br><br>

  <br><br>
  <input type="submit" value="Submit">
</form>

</body>
</html>

schoolproject/schoolproject/templates/newpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inmakes School</title>
</head>
<body>
<center>
    <h1 style="color:#118FC9;font-family:Garamond"><u>Student Registration</u></h1><br><br>
    <form>
    {% csrf_token %}
       <button> <a href="{% url 'credentials:form' %}">Go to Store</a></button>
    </form>
</center>
</body>
</html>

schoolproject/schoolproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-image:url({% static 'img/bg.jpg' %})">
<center>
    <h1 style="color:#118FC9;font-family:Garamond"><u>REGISTRATION FORM</u></h1><br><br>
        <form action="{% url 'credentials:register' %}" method="post" >
            {% csrf_token %}
            <label><b>Username:</b></label>&nbsp;&nbsp;
            <input type="text" name="username" placeholder="Username"><br><br>
            <label><b>Password:&nbsp;</b></label>
            <input type="password" name="pd" placeholder="Password"><br><br>
            <label><b>Confirm :</b></label>
            <input type="password" name="cpd" placeholder="Confirm Password"><br><br>

            <input type="submit" name="login">



        </form>
    {% for msg in messages %}
    <h2 style="color:white;">{{msg}}</h2>
    {% endfor %}
</center>
</body>
</html>